### ISSUE TITLE
debugging workspace

### ISSUE THREAD

**Issue by RMHogervorst** [RMHogervorst/dagster_rpi3#1]
There are 2 ways to load jobs, schedules etc. in your workspace.yaml

1. `python_file` refering to repo.py:

```yaml
load_from:
  - python_file:
      relative_path: work/repo.py
      working_directory: work
```

2. loading from python package 

```yaml
load_from:
  - python_package:
      package_name: work
```

I have a setup.py (see below)
I installed that package in the virtual env `pip install -e .`

When I run dagit from the root folder I can't get the second one to work. 
```
UserWarning: Error loading repository location work:dagster.core.errors.D
agsterInvariantViolationError: No jobs, pipelines, graphs, asset collections, or repositories found
in "work".
```

What am I missing here?

This is my project
```
├── README.md
├── __init__.py
├── logs
├── setup.py
├── work
|	├── README.md
|	├── jobs
|	├── ops
|	├── repo.py
|	├── resources
|	└── sql
├── work_dbt
├── work_tests
└── workspace.yaml
```

This is the setup.py
```python
from setuptools import find_packages, setup

setup(
    name="work",
    version="0+dev",
    author="Roel",
    classifiers=[
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Operating System :: OS Independent",
    ],
    packages=["work"],
    install_requires=[
        "dagit==0.14.7",
        "dagster==0.14.7",
        "dagster-dbt==0.14.7",
        "SQLAlchemy==1.4.35"
        ]
)

```
